import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import { WalletProviderClientWrapper } from "@/components/Txn-lab/WalletProviderClientWrapper";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WalletProviderClientWrapper>
          <Toaster />
          <Navbar />
          {children}
        </WalletProviderClientWrapper>
      </body>
    </html>
  );
}
